language: java
jdk:
  - oraclejdk11
branches:
  only:
    - master
before_install:
  - chmod +x ./gradlew
services:
  - xvfb
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_script:
  - bash <(curl -s https://codecov.io/bash -t "$CODECOV_TOKEN")